// Generated by CoffeeScript 1.8.0
(function() {
  var book;

  MBP.scaleFix();

  MBP.hideUrlBarOnLoad();

  MBP.preventScrolling();

  MBP.preventZoom();

  book = {
    stories: {
      splash: function() {
        var nom;
        nom = 'splash';
        console.log('storyStart ' + nom);
        $('.story').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      login: function() {
        var nom;
        nom = 'login';
        console.log('storyStart ' + nom);
        $('.story').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      sliding_menu: function() {
        var nom;
        nom = 'sliding_menu';
        console.log('storyStart ' + nom);
        $('.story').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      app: function() {
        var nom;
        nom = 'app';
        console.log('storyStart ' + nom);
        $('.story').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      mag: function() {
        var nom;
        this.app();
        nom = 'mag';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      a_la_une: function() {
        var nom;
        this.mag();
        nom = 'a_la_une';
        console.log('storyStart ' + nom);
        $('.story-app-mag').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      actualites: function() {
        var nom;
        this.mag();
        nom = 'actualites';
        console.log('storyStart ' + nom);
        $('.story-app-mag').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      focus: function() {
        var nom;
        this.mag();
        nom = 'focus';
        console.log('storyStart ' + nom);
        $('.story-app-mag').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      mes_articles: function() {
        var nom;
        this.mag();
        nom = 'mes_articles';
        console.log('storyStart ' + nom);
        $('.story-app-mag').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      texte_cgv: function() {
        var nom;
        this.app();
        nom = 'texte_cgv';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      texte_confi: function() {
        var nom;
        this.app();
        nom = 'texte_confi';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      res_recherche: function() {
        var nom;
        this.app();
        nom = 'res_recherche';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      ajouter_tuile: function() {
        var nom;
        this.app();
        nom = 'ajouter_tuile';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      mon_compte: function() {
        var nom;
        this.app();
        nom = 'mon_compte';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      },
      article_ouvert: function() {
        var nom;
        this.app();
        nom = 'article_ouvert';
        console.log('storyStart ' + nom);
        $('.story-app').addClass('invisible');
        return $('#' + nom).removeClass('invisible');
      }
    },
    storyStart: function(div) {
      return this.stories[div]();
    },
    storyTell: function(element) {
      return this.storyStart('splash');
    }
  };

  window.book = book;

  window.book.storyTell();

}).call(this);
