// Generated by CoffeeScript 1.8.0
(function() {
  var book;

  MBP.hideUrlBarOnLoad();

  MBP.scaleFix();

  MBP.preventScrolling();

  MBP.preventZoom();

  book = {
    storiesList: null,
    displayStory: function(storyName) {
      var i, _i, _len, _ref;
      console.log("displayStory " + storyName);
      $('.story, .story-app, .story-app-mag').addClass('invisible');
      _ref = Object.getOwnPropertyNames(book.stories[storyName].show);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        $('#' + book.stories[storyName].show[i]).removeClass('invisible');
      }
      if (book.stories[storyName].set) {
        return book.stories[storyName].set();
      }
    },
    stories: {
      splash: {
        show: ['splash']
      },
      login: {
        show: ['login']
      },
      a_la_une: {
        show: ['app', 'mag', 'a_la_une']
      },
      actualites: {
        show: ['app', 'mag', 'actualites']
      },
      focus: {
        show: ['app', 'mag', 'focus']
      },
      mes_articles: {
        show: ['app', 'mag', 'mes_articles']
      },
      sliding_menu: {
        show: [],
        set: function() {
          return $('#sliding_menu').toggleClass('invisible');
        }
      },
      texte_cgv: {
        show: ['app', 'texte_cgv']
      },
      texte_confi: {
        show: ['app', 'texte_confi']
      },
      res_recherche: {
        show: ['app', 'res_recherche']
      },
      article_ouvert: {
        show: ['app', 'article_ouvert']
      },
      ajouter_tuile: {
        show: ['app', 'ajouter_tuile']
      },
      mon_compte: {
        show: ['app', 'mon_compte']
      }
    },
    storyTell: function(div) {
      return book.displayStory(div);
    },
    storyAsk: function(element) {
      return book.storyTell('splash');
    },
    navigate: {
      cursor: 0,
      size: 0,
      next: function() {
        if (this.cursor + 1 >= this.size) {
          this.cursor = 0;
        } else {
          this.cursor += 1;
        }
        return book.displayStory(book.storiesList[this.cursor]);
      },
      prev: function() {
        if (this.cursor - 1 <= 0) {
          this.cursor = this.size - 1;
        } else {
          this.cursor -= 1;
        }
        return book.displayStory(book.storiesList[this.cursor]);
      }
    }
  };

  window.book = book;

  $(document).ready(function() {
    book.storiesList = Object.getOwnPropertyNames(window.book.stories);
    book.navigate.size = book.storiesList.length;
    window.mySwipe = $('#slider');
    $(window.document).keypress(function(e) {
      if (e.charCode === 102) {
        window.book.navigate.next();
      }
      if (e.charCode === 101) {
        return window.book.navigate.prev();
      }
    });
    return window.book.storyAsk();
  });

}).call(this);
